[package]
name = "huawei-hash-bruteforce"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "unlock"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
tokio = { version = "1.0", features = ["full", "process"] }
sha2 = "0.10"
hex = "0.4"
